### ISSUE TITLE
Implement unified-engine

### ISSUE THREAD

**Issue by remcohaszing** [unifiedjs/unified-language-server#11]
### Initial checklist

- [X] I read the [support docs](https://github.com/unifiedjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/unifiedjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/unifiedjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aunifiedjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

As part of https://github.com/remarkjs/remark/discussions/910 I would like to make `unified-language-server` based on `unified-engine`, so it yields the same result as CLIs created using `unified-args`.

Currently the language server is written in CJS, has a custom configuration file, and is synchronous. Unfortunately this means a lot of the existing code needs to be rewritten. Fortunately this also means a lot of code can be removed.

In order to do this right, the command line interface of the language server needs to be redesigned.

### Solution

I imagine the CLI works like this:

```sh
unified-language-server \
  --prefix remark \
  --plugin remark-parse \
  --plugin remark-stringify
```

- `--prefix` defines the prefix that’s passed to `unified-engine`. I.e. the example loads `.remarkrc.js`, `.remarkignore`, etc.
- `--plugin` specifies plugins to be loaded that aren’t defined in the configuration file. They will be loaded using [`load-plugin`](https://www.npmjs.com/package/load-plugin).

Also I suggest we add a pre existing command line parser, i.e. [`commander`](https://www.npmjs.com/package/commander)

### Alternatives

Another possibility is to load `remark`. This better matches behavior of `remark-cli`. However, I’m not sure how this should be defined, because `remark` uses a named export.

**Comment by wooorm** [comment]
- why not model `--plugin` (and other args) after [`unified-args`](https://github.com/unifiedjs/unified-args). also, `packageField`, `extensions`?
- the engine can already load plugins

Isn’t the first step btw to rewrite as async?
