### ISSUE TITLE
Add unified-language-server to vim-lsp-settings

### ISSUE THREAD

**Issue by remcohaszing** [unifiedjs/unified-language-server#12]
### Initial checklist

- [X] I read the [support docs](https://github.com/unifiedjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/unifiedjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/unifiedjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aunifiedjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

`unified-language-server` has the potential to work great for [`vim-lsp`](https://github.com/prabirshrestha/vim-lsp) users editing markdown files. However, it’s a bit annoying to set up.

### Solution

If it’s registered to [`vim-lsp-settings`](https://github.com/mattn/vim-lsp-settings), it can be configured using a single command.

### Alternatives

:shrug:

**Comment by Murderlon** [comment]
Would be even greater to create an official Neovim LSP config for it, [like these](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md). Since Neovim 0.5, native LSP support is build-in, removing the need for something like `vim-lsp`. With the added config, users only have to do `require'lspconfig'.remark.setup{}` (or `unified`).

**Comment by remcohaszing** [comment]
> Would be even greater to create an official Neovim LSP config for it, [like these](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md). Since Neovim 0.5, native LSP support is build-in, removing the need for something like `vim-lsp`. With the added config, users only have to do `require'lspconfig'.remark.setup{}` (or `unified`).

Sounds great!

---

I have to admit I’m mainly interesting in working towards https://github.com/remarkjs/remark/discussions/910. `vim-lsp` is something I stumbled upon, because I was looking for a way to test this project manually. I use vim for simple things, but I’m not familiar with Neovim.

**Comment by remcohaszing** [comment]
Done!

https://github.com/mattn/vim-lsp-settings/pull/516
