### ISSUE TITLE
Add documentation for more editors

### ISSUE THREAD

**Issue by ChristianMurphy** [unifiedjs/unified-language-server#2]
### Subject of the feature

Document usage in more editors

### Problem

Language servers are designed to be usable with almost any editor.
Currently only NeoVim usage is documented.

### Expected behaviour

Include documentation for other editors, including:
* VSCode
* Vim
* Emacs
* SublimeText
* Atom

https://langserver.org/#implementations-client

### Alternatives

Link to external documentation

**Comment by wooorm** [comment]
@ChristianMurphy I think this is superseded by [4](https://github.com/remarkjs/remark-language-server/pull/4), and since `unified-language-server` is now a building block, which has example implementations such as `remark-language-server`, we don’t need to add docs here?
