### ISSUE TITLE
`file.cwd` is not correctly set

### ISSUE THREAD

**Issue by wooorm** [unifiedjs/unified-language-server#20]
### Initial checklist

- [X] I read the [support docs](https://github.com/unifiedjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/unifiedjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/unifiedjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aunifiedjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

latest

### Steps to reproduce

`cwd` is not set when [creating a file](https://github.com/unifiedjs/unified-language-server/blob/e0ffb7fb8e1e2418a1fc6487b1ef6197d4290617/lib/index.js#L127-L134) or when [creating an engine](https://github.com/unifiedjs/unified-language-server/blob/e0ffb7fb8e1e2418a1fc6487b1ef6197d4290617/lib/index.js#L164-L177).

`file.cwd` must be set to the folder that is the “workplace”, e.g., the place where the `package.json` and `.git` are typically.
Right now, it’s not set, so it’s (90% sure) set to a wrong value. Which means certain plugins break (example: https://github.com/remarkjs/remark-usage/blob/ae591a38bfb5424a802f25ae77b69f5dc06836fa/lib/index.js#L13-L27)

### Expected behavior

Here’s how I found a logical one for atom: https://github.com/unifiedjs/unified-engine-atom/blob/605326d08a6d04b66aa8abf3143313f24c507699/index.js#L44-L53

### Actual behavior

(unknown behavior, likely broken plugins or unexpected results)

**Comment by remcohaszing** [comment]
Isn’t it set to `process.cwd()` by default? Typically the client determines the `cwd`.

Also does it make sense if `unified-engine` detects this? I imagine a good `cwd` to set would be the directory containing the configuration file.

**Comment by wooorm** [comment]
Yes, but the value provided by `process.cwd` does not always make sense.
Atom sets it to `/` (which is why `remark-parse` can’t be resolved and why `linter-remark` doesn’t work with the PR)
I’m also guessing the Node.js language server runs in a `cwd` that is different from the “workspace”, as they‘re separate processed?

`unified-engine` has an option for it: `options.cwd`, which can be given the CWD. This can (should?) be set too.

> I imagine a good cwd to set would be the directory containing the configuration file.

Files are found first, configuration files are found from them. That means that there can be a) multiple configuration files, b) none, c) one in say, `/Users/`

**Comment by ChristianMurphy** [comment]
Maybe the workspace folders(s) could be used? https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#workspace_workspaceFolders

**Comment by wooorm** [comment]
Nice that LSP also has that. For Atom, the earlier linked lines (https://github.com/unifiedjs/unified-engine-atom/blob/605326d08a6d04b66aa8abf3143313f24c507699/index.js#L44-L53) uses something like that too.

**Comment by remcohaszing** [comment]
Yes, I think using `rootUri` of the `InitializeParams` should be used.
