### ISSUE TITLE
Smarter file processing

### ISSUE THREAD

**Issue by wooorm** [unifiedjs/unified-language-server#25]
### Initial checklist

- [X] I read the [support docs](https://github.com/unifiedjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/unifiedjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/unifiedjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aunifiedjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

`workspace/didChangeWatchedFiles` means *a* file or folder changed. https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_didChangeWatchedFiles. Instead of reprocessing every markdown file (https://github.com/unifiedjs/unified-language-server/blob/f222a6552e04c50c4bf6933b0539898ece9c47ff/lib/index.js#L264).

### Solution

perhaps we should use cheap hashes to ensure we only perform work when something changed.

### Alternatives

n/a

**Comment by remcohaszing** [comment]
> ### Problem
> `workspace/didChangeWatchedFiles` means _a_ file or folder changed. https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_didChangeWatchedFiles. Instead of reprocessing every markdown file

This doesn’t mean **a file** has changed. It means **a watched file** has changed.

How this is used can be seen in `remark-vscode`: https://github.com/remarkjs/vscode-remark/blob/2f1cb9916651e1cb19ede823f2bf0ffdb3aa8af8/src/extension.js#L27-L32

So if **a configuration file** changes, all documents are checked again.

**Comment by wooorm** [comment]
That is an important caveat that seems like it’s something that should be in a comment next to the function?

**Comment by remcohaszing** [comment]
Maybe in the readme for `workspace/didChangeWatchedFiles` add somethink like:

> Clients are expected to watch the remark configuration files.

**Comment by wooorm** [comment]
I’m okay on that too, but probably also perhaps a new section (Client?) on how to make a client (because Use should be one basic example, and API should be just about options)

**Comment by remcohaszing** [comment]
I think that’s basically what the `Language Server features` section is.

**Comment by wooorm** [comment]
It is the items in that list, and could be that section, but the current wording is different than what I’m looking for. That section currently explains what the code is doing.

I’m looking for a list that explains what requests and notifications, must/should/could be sent, and when, by clients.
And a list of things that are sent by the server back to the client, and how the client should respond to that.
