### ISSUE TITLE
Support vfile message `note`

### ISSUE THREAD

**Issue by remcohaszing** [unifiedjs/unified-language-server#26]
### Initial checklist

- [X] I read the [support docs](https://github.com/unifiedjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/unifiedjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/unifiedjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aunifiedjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Some unified plugins support the [`vfile-message#note`](https://github.com/vfile/vfile-message#note) property. It might be nice to support this in the language server as well.

### Solution

If `note` is define on a vfile message, add it to the diagnostic message joined by 1 or 2 newlines.

### Alternatives

1. Don’t support it
2. Make it customizable. This is more work and I think users are unlikely to explicitly enable or disable this.

**Comment by remcohaszing** [comment]
I personally had my doubts about multiline diagnostics when I started this, so for comparision: ESLint diagnostics typically fit on one line, but TypeScript diagnostics tend to display an entire trace if where the error comes from.

**Comment by wooorm** [comment]
There is some markdown support in LSP right? But I don’t think for messages? That would be cool...

**Comment by remcohaszing** [comment]
Markdown is supported for hover effects (used for JSDoc / the non-standard `"markdownDescription"` in JSON schema), but it’s not supported for diagnostics.
