### ISSUE TITLE
Incremental processing

### ISSUE THREAD

**Issue by ChristianMurphy** [unifiedjs/unified-language-server#3]
### Subject of the feature

Review AST and only reprocess segments that have been changed.

### Problem

Large documents can be slow to reparse as you type.

### Expected behaviour

Only lint/review parts of the document that have changed.
Allowing for faster feedback.

### Alternatives

https://github.com/micromark/micromark for incremental parsing.

### Note

This may not be possible with the current design of unified.
Thoughts on how it may be achievable are welcome.

**Comment by wooorm** [comment]
@remcohaszing Any thoughts on this?

I think this is probably a `no/wontfix` as it can’t be done with unified?

**Comment by remcohaszing** [comment]
I agree this is unlikely to be implemented. It would need upstream updates in unified and parsers first.

**Comment by wooorm** [comment]
Closing then as a wontfix, as it most likely won’t be implemented in the next few years?
Though, if someone wants to try their hands at it, :+1:
