### ISSUE TITLE
Rewrite global console to output to the language server connection console

### ISSUE THREAD

**Issue by remcohaszing** [unifiedjs/unified-language-server#41]
### Initial checklist

- [X] I read the [support docs](https://github.com/unifiedjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/unifiedjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/unifiedjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aunifiedjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

If the server uses the stdio protocol for communication, stdout is used for communication. However, `console.log()` etc statements also write to stdout. This causes the following error:

```
node_modules/vscode-jsonrpc/lib/common/messageReader.js:138
                    throw new Error('Header must provide a Content-Length property.');
                    ^

Error: Header must provide a Content-Length property.
    at StreamMessageReader.onData (node_modules/vscode-jsonrpc/lib/common/messageReader.js:138:27)
    at Socket.<anonymous> (node_modules/vscode-jsonrpc/lib/common/messageReader.js:122:18)
    at Socket.emit (node:events:520:28)
```

The language server simply shouldn’t use `console.log()`, but third party plugins or other third party packages might do so.

### Solution

The language server can rewrite the global console, so its calls are rerouted to `connection.console`.

### Alternatives

The output could be disabled entirely.

**Comment by remcohaszing** [comment]
This has been solved upstream. It’s a matter of waiting for a new release now.

**Comment by wooorm** [comment]
nice!
