### ISSUE TITLE
Contributing to unified projects, including as a maintainer, is a voluntary endeavour (it is unpaid). There are no scores. Contributing more doesn’t necessarily mean you get voting rights. Everybody (except for me) is doing this next to their day job.

### ISSUE THREAD

**Issue by Vantu432** [unifiedjs/unified-language-server#65]
Contributing to unified projects, including as a maintainer, is a voluntary endeavour (it is unpaid). There are no scores. Contributing more doesn’t necessarily mean you get voting rights. Everybody (except for me) is doing this next to their day job.

I currently am paid for part-time project leadership.

_Originally posted by @wooorm in https://github.com/unifiedjs/collective/issues/34#issuecomment-566069313_

**Comment by ChristianMurphy** [comment]
Please stop spamming issues
