### ISSUE TITLE
jsonrpc error thrown

### ISSUE THREAD

**Issue by 573** [unifiedjs/unified-language-server#7]
In a markdown file

Server is running responding `1` (`:call LanguageClient_isServerRunning()`)

When I do `:call LanguageClient#textDocument_formatting()` I get

>[LC] Error: Failure { jsonrpc: Some(V2), error: Error { code: MethodNotFound, message: "Unhandled method textDocument/formatting", data: None }, id: Num(2) }

**Comment by wooorm** [comment]
Hey! This project was rewritten recently. It’s a lot better now, so probably no longer fails on this.
Could you try it out and report back if it’s still an error?
