### ISSUE TITLE
Ability to specify configuration file as command-line argument

### ISSUE THREAD

**Issue by hjpotter92** [unifiedjs/unified-language-server#8]
### Subject of the feature

Better documentation around handling of configuration file, or specifying config file as an argument when starting server

### Problem

Currently, the docs do not make it clear where and how the configuration file is supposed to be sent to server.

**Comment by ChristianMurphy** [comment]
https://github.com/unifiedjs/unified-language-server/blob/main/CONFIGURATION.md#for-neovim

Documents where to add the configuration file.
settings.json in the home folder

**Comment by ChristianMurphy** [comment]
Here is where the configuration is passed to the server

https://github.com/unifiedjs/unified-language-server/blob/ca717b1322a9ff09cbea3442505929a7ae00327c/src/index.js#L52-L65

https://github.com/unifiedjs/unified-language-server/blob/ca717b1322a9ff09cbea3442505929a7ae00327c/src/server.js#L153-L157

**Comment by hjpotter92** [comment]
Thanks, I've implemented the same over in emacs :)

https://github.com/emacs-lsp/lsp-mode/pull/2800
